# -*- coding: utf-8 -*-
"""Copia de resistencias y capacitores 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R5CZvR7Zc3jZTD0XrY3LMTX61zgddk1O
"""

import numpy as np
from scipy.optimize import milp, LinearConstraint, Bounds

# La función objetivo a maximizar es
# z = 25x + 50y

# Las restricciones son:
# x+y≤90
# 4x+6y≥390
# 15x+40y≤2000
# x,y≥0

# coeficientes de la función objetivo (negativos porque linprog minimiza)
c = [-2, -3, -5, -4, -6, -8]

# coeficientes de las variables en las restricciones
A = [
    [1,1,1,0,0,0], #limite total de resistencias
    [0,0,0,1,1,1], #limite total de condensadores
    [0.5,0.7,0.9,0.8,1.0,1.2], #tiempo de produccion
    [0.01,0.015,0.02,0.05,0.08,0.1], #material disponible
    [-1,-1,0,0,1,1] #condensadores grandes - resisencias pequeñas
    ]

# cotas superiores en las restricciones
bu = [1000, 800, 2000, 50, 0]
bl = [0, 0, 0, 0, 0]

constraints = LinearConstraint(A, bl, bu)
bounds = Bounds([0]*6, [np.inf]*6) #Acá le decimos que las variables son positivas.

res = milp(
    c=c,
    constraints=constraints,
    bounds=bounds,
    integrality=[0]*6
)
# Esto significa que para x,y si es 0 resuelve en continua, si es 1 resuelve en enteros

print("Estado:", res.message)
print("F =", -res.fun) #Ponemos un menos porque minimizó la función -F(x,y)
print("x =", res.x[0])
print("y =", res.x[1])
print(res.x)

